config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_for :admins, controllers: { sessions: 'admins/sessions' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :events , shallow: true do
        resources :comments
      end
      resources :comments
    end
  end


  resources :users, defaults: { format: :html}
  resources :comments, defaults: { format: :html}
  resources :events, defaults: { format: :html}
  resources :event_creators, defaults: { format: :html}
  resources :event_guests, defaults: { format: :html}
  resources :invitations, defaults: { format: :html}
  resources :mailboxes, defaults: { format: :html}
  resources :organizations, defaults: { format: :html}
  resources :organization_administrators, defaults: { format: :html}
  resources :replies, defaults: { format: :html}
  resources :start_date_options, defaults: { format: :html}
  resources :votes, defaults: { format: :html}
  resources :searches, default: { format: :html}
  resources :messages, defaults: {format: :html}
  resources :aup, default: { format: :html}
  resources :to_s, default: { format: :html}
  resources :event_reports, default: { format: :html}
  resources :comment_reports, default: { format: :html}
  resources :organization_reports, default: { format: :html}
  resource :total_report, default: { format: :html}
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

end

app/models/start_date_option.rb
class StartDateOption < ApplicationRecord
  belongs_to :event
  has_many :votes, dependent: :destroy

  validate :custom_validation_method_with_message

  def custom_validation_method_with_message
    if possiblestartdate.blank?
      errors.add(:_, "can't be blank")
    end
  end


end

app/controllers/start_date_options_controller.rb
class StartDateOptionsController < ApplicationController
  before_action :set_start_date_option, only: [:show, :edit, :update, :destroy]

  # GET /start_date_options
  # GET /start_date_options.json
  def index
    @start_date_options = StartDateOption.all
  end

  # GET /start_date_options/1
  # GET /start_date_options/1.json
  def show
  end

  # GET /start_date_options/new
  def new
    @start_date_option = StartDateOption.new
  end

  # GET /start_date_options/1/edit
  def edit
  end

  # POST /start_date_options
  # POST /start_date_options.json
  def create
    @start_date_option = StartDateOption.new(start_date_option_params)

    respond_to do |format|
      if @start_date_option.save
        format.html { redirect_to @start_date_option, notice: 'Start date option was successfully created.' }
        format.json { render :show, status: :created, location: @start_date_option }
      else
        format.html { render :new }
        format.json { render json: @start_date_option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /start_date_options/1
  # PATCH/PUT /start_date_options/1.json
  def update
    respond_to do |format|
      if @start_date_option.update(start_date_option_params)
        format.html { redirect_to @start_date_option, notice: 'Start date option was successfully updated.' }
        format.json { render :show, status: :ok, location: @start_date_option }
      else
        format.html { render :edit }
        format.json { render json: @start_date_option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /start_date_options/1
  # DELETE /start_date_options/1.json
  def destroy
    @start_date_option.destroy
    respond_to do |format|
      format.html { redirect_to start_date_options_url, notice: 'Start date option was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_start_date_option
      @start_date_option = StartDateOption.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def start_date_option_params
      params.fetch(:start_date_option, {})
    end
end

app/helpers/start_date_options_helper.rb
module StartDateOptionsHelper
end

app/views/start_date_options/_form.html.erb
<%= form_with(model: start_date_option, local: true) do |form| %>
  <% if start_date_option.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(start_date_option.errors.count, "error") %> prohibited this start_date_option from being saved:</h2>

      <ul>
        <% start_date_option.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/start_date_options/edit.html.erb
<h1>Editing Start Date Option</h1>

<%= render 'form', start_date_option: @start_date_option %>

<%= link_to 'Show', @start_date_option %> |
<%= link_to 'Back', start_date_options_path %>

app/views/start_date_options/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Start Date Options</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @start_date_options.each do |start_date_option| %>
      <tr>
        <td><%= link_to 'Show', start_date_option %></td>
        <td><%= link_to 'Edit', edit_start_date_option_path(start_date_option) %></td>
        <td><%= link_to 'Destroy', start_date_option, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Start Date Option', new_start_date_option_path %>

app/views/start_date_options/new.html.erb
<h1>New Start Date Option</h1>

<%= render 'form', start_date_option: @start_date_option %>

<%= link_to 'Back', start_date_options_path %>

app/views/start_date_options/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_start_date_option_path(@start_date_option) %> |
<%= link_to 'Back', start_date_options_path %>