config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_for :admins, controllers: { sessions: 'admins/sessions' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :events , shallow: true do
        resources :comments
      end
      resources :comments
    end
  end


  resources :users, defaults: { format: :html}
  resources :comments, defaults: { format: :html}
  resources :events, defaults: { format: :html}
  resources :event_creators, defaults: { format: :html}
  resources :event_guests, defaults: { format: :html}
  resources :invitations, defaults: { format: :html}
  resources :mailboxes, defaults: { format: :html}
  resources :organizations, defaults: { format: :html}
  resources :organization_administrators, defaults: { format: :html}
  resources :replies, defaults: { format: :html}
  resources :start_date_options, defaults: { format: :html}
  resources :votes, defaults: { format: :html}
  resources :searches, default: { format: :html}
  resources :messages, defaults: {format: :html}
  resources :aup, default: { format: :html}
  resources :to_s, default: { format: :html}
  resources :event_reports, default: { format: :html}
  resources :comment_reports, default: { format: :html}
  resources :organization_reports, default: { format: :html}
  resource :total_report, default: { format: :html}
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :event_creator
  belongs_to :organization
  has_many :comments, dependent: :destroy
  has_many :replies, through: :comments
  has_many :event_guests ,dependent: :destroy
  has_many :invitations, dependent: :destroy
  has_many :start_date_options , dependent: :destroy
  has_many :votes ,through: :start_date_options

  accepts_nested_attributes_for :start_date_options
  has_one_attached :event_picture

  has_many_attached :pdf
  has_many_attached :pictures
  has_many_attached :videos


  validates :name, :location, :description, presence: true

  validate :custom_validation_method_with_message

  def custom_validation_method_with_message
    if finalVotingDay.blank?
      errors.add( :_,"Final voting day can't be blank")
    end
  end


end

app/controllers/api/v1/events_controller.rb
class API::V1::EventsController < APIController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /api/v1/events/:id
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /api/v1/events
  def create
    @event = Event.new(event_params)
    @event.event_creator = EventCreator.find(params[:event_creator_id])
    @event.organization = Organization.find(params[:organization_id])


    if @event.save
      render :show, status: :created, location: @event
    else
      render json: @event.errors, status: :unprocessable_entity
    end
  end


  # PATCH/PUT /api/v1/events/1
  def update
    if @event.update(event_params)
      render :show, status: :ok, location: api_v1_events_path(@event)
    else
      render json: @event.errors, status: :unprocessable_entity
    end
  end

  # DELETE /api/v1/events/1
  def destroy
    @event.destroy
    head :no_content
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.fetch(:event, {}).permit(:id, :name, :location , :description, :picture, :publicEvent, :event_creator_id, :organization_id )
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event_comments= @event.comments
    @user = User.find(params[:id])
  end

  # GET /events/new
  def new
    @event = Event.new
    2.times { @event.start_date_options.build }
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.fetch(:event, {}).permit(:id,:name,:description,:location,:public_event,:event_picture, :event_creator_id, :organization_id,:finalVotingDay, start_date_options_attributes: [:id, :possiblestartdate], pdf: [], pictures: [], videos: [])
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div class="card page-background mx-auto w-50 mt-2 mb-2">
  <h3> <i class="fas fa-calendar-alt mr-2"></i><%= link_to event.name, event, class: "text-info" %></h3>
  <% if event.organization != nil%>
    <p>This event belongs to the organization: </p>
      <h6><%= link_to event.organization.name , event.organization, class: "text-info"%></h6>

  <%else %>
    <p>This event doesn't belongs to any organization </p>
  <%end %>
</div>

app/views/events/_form.html.erb
<div>
  <%= form_with model: event, local: true do |form| %>
    <%= errors_for event%>

    <% if user_signed_in? %>
    <%= form.hidden_field :event_creator_id , value: current_user.event_creator.id%>
    <%= form.hidden_field :organization_id , value: current_user.organization_id%>
      <%end %>


    <div class="container emp-profile">
      <form method="post">
        <div  id=profile_row class="row m-0 p-0">
          <div class="col-md-4 ml-0">
            <div class="profile-img ">
              <% if @event.event_picture.attached? %>
                <%= image_tag(@event.event_picture, class: "card-img-top", height: "150px", background: "#55595c", color: "#eceeef")%>
              <% else %>
                <%=image_tag("thumbnail.svg", class: "card-img-top", height: "150px", background:"#55595c", color: "#eceeef") %>
              <% end %>
              <div class=" form-group m-0 p-0">
                <%= form.file_field :event_picture, class: " file btn form-control-file" %>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="profile-head">
              <div>
                <h6>
                  <div class="form-group">
                    <i class="fas fa-info-circle"> </i>
                    <%= form.label :name%>
                    <%= form.text_field :name , class: "form-control"%>
                  </div>
                </h6>
              </div>
              <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item ">
                  <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">About</a>
                </li>
                <% if @event.new_record? %>
                <li class="nav-item">
                  <a class="nav-link" id="profile-tab" data-toggle="tab" href="#startdatepoll" role="tab" aria-controls="profile" aria-selected="false">Start Date Poll Setup</a>
                </li>
                  <%end%>
              </ul>
            </div>
          </div>
          <div class="col-md-4">
            <div class="profile-head">
              <div>
                <h6>
                  <div class="form-group">
                    <i class="fas fa-location-arrow"> </i>
                    <%= form.label :location%>
                    <%= form.text_field :location , class: "form-control"%>
                  </div>
                </h6>
              </div>
            </div>
          </div>

        </div>
        <div class="row">
          <div class="col-md-4 pt-5 ml-3">
            <div class="profile-work">
            </div>
          </div>

          <div class="col-md-7">
            <div class="tab-content profile-tab" id="myTabContent">
              <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                <div class="row pt-2">
                  <div class="col-md-12">
                    <div class="form-group pt-1">
                      <%= form.label :description%>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <%= form.text_area :description, class: "form-control" %>
                  </div>
                  <% if admin_signed_in? %>
                    <div class="col-md-12">
                      <%= form.label :event_creator %>
                      <%= form.collection_select :event_creator_id, User.all,:id,:username, include_blank: true ,class: "form-control"%>
                    </div>

                    <div class="col-md-12">
                      <%= form.label :Organization %>
                      <%= form.collection_select :organization_id, Organization.all,:id,:name, include_blank: true ,class: "form-control"%>
                    </div>
                  <%end %>
                </div>
              </div>

              <div class="tab-pane fade" id="startdatepoll" role="tabpanel" aria-labelledby="profile-tab">
                <% @count=1 %>
                <div class="row mb-3 mt-3">
                  <div class="text-center">
                    <p class="ml-3">Set Final Voting Day</p>
                    <%= form.datetime_field  :finalVotingDay , class: "form-control" %>
                  </div>
                </div>
                  <%= form.fields_for :start_date_options do |option| %>
                    <div class="row mb-3 mt-3">
                      <div class="text-center">
                        <p class="ml-3">Create date option <%=@count %></p>
                        <%= option.datetime_field :possiblestartdate , class: "form-control" %>
                      </div>
                    </div>
                  <% @count+=1 %>
                <%end %>
              </div>
            </div>
          </div>
        </div>
      </form>
      <div class="form-group mt-2 text-center">
        <%= form.submit submit_btn_text, class: ["btn", "btn-primary"] %>
        <%= link_to "Back", :back, class: ["btn", "btn-secondary"] %>
      </div>
    </div>
  <% end %>
</div>

app/views/events/edit.html.erb
<div class="ml-0 mt-3 text-center">
  <h2>Edit "<%=@event.name%>" Event</h2>
</div>
<div class="ml-0 mt-2 text-center">
  <p>Please enter the required information to edit the "<%=@event.name%>" event:</p>
</div>
<%= render partial: "form",
           locals: {
               event: @event,
               submit_btn_text: "Update"
           } %>

app/views/events/index.html.erb
<div class="text-center">
  <h3 class="big_title">Events</h3>

  <a class="big_title badge badge-pill bg-primary text-light mb-4" <%= link_to "Create New Event",new_event_path %></a>
  <% @events.each do |event| %>
    <div class="card mb-4 shadow-sm mx-auto w-50">
      <div class="card-header">
        <h3 id="event_org"><%= event.name %></h3>
      </div>
      <% if event.event_picture.attached? %>
        <%= link_to image_tag(event.event_picture, class: "card-img-top", height: "318.75px" ,background: "#55595c", color: "#eceeef"), url_for(event) %>
      <% else %>
        <%=link_to image_tag("thumbnail.svg", class: "card-img-top", background:"#55595c", color: "#eceeef") , url_for(event)%>
      <% end %>
      <div class="card-body">
        <p class="card-text">Description: <%= event.description%></p>
        <p class="card-text"><i class="fas fa-location-arrow mr-1 fa-lg"> </i> <%= event.location %></p>
        <button type="button" class="btn btn-sm btn-outline-secondary"> <%= link_to "See event" , event%></button>
      </div>
    </div>
  <% end %>
</div>

app/views/events/new.html.erb
<div class="ml-0 mt-3 text-center">
  <h2>Create New Event</h2>
</div>
<div class="ml-0 mt-2 text-center">
  <p>Please enter the required information to create a new event:</p>
</div>
<%= render partial: "form",
           locals: {
               event: @event,
               submit_btn_text: "Create"
           } %>

app/views/events/show.html.erb
<div class="container emp-profile">
  <form method="post">
    <div class="row">
      <div class="col-md-4">
        <div class="profile-img">
          <% if @event.event_picture.attached? %>
            <%= image_tag(@event.event_picture, class: "card-img-top", height: "150px", background: "#55595c", color: "#eceeef")%>
          <% else %>
            <%=image_tag("thumbnail.svg", class: "card-img-top", height: "150px", background:"#55595c", color: "#eceeef") %>
          <% end %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="profile-head">
          <h4>
            <%= @event.name%>
          </h4>
          <h6>
            <i class="fas fa-location-arrow mr-1 fa-lg"> </i> <%= @event.location %>
          </h6>
          <h6>
            <i class="fas fa-info-circle mr-1 fa-lg"> </i> <%= @event.description %>
          </h6>
          <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item">
              <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Guests</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="profile-tab" data-toggle="tab" href="#comments" role="tab" aria-controls="profile" aria-selected="false">Comments</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="profile-tab" data-toggle="tab" href="#start_date_poll" role="tab" aria-controls="profile" aria-selected="false">Start Date Poll</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="profile-tab" data-toggle="tab" href="#attachments" role="tab" aria-controls="profile" aria-selected="false">Attachments</a>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md-2">
        <% if user_signed_in? %>
          <% if current_user.id==@event.event_creator.user.id %>
        <div class="row">
          <%= link_to "Edit Event", edit_event_path , class: "profile-edit-btn mr-1 text-info"%>
        </div>
        <div class="row">
          <%= link_to 'Delete Event', event_path(@event), method: :delete, data: { confirm: 'Are you sure?' } , class: "profile-edit-btn mt-1 text-danger"%>
        </div>

          <div class="row">
            <%= link_to "Invite Guest", new_invitation_path(event_id:@event.id) , class: "profile-edit-btn mr-1 text-success"%>
          </div>
          <% else %>
            <div class="row">
              <%= link_to 'Report Event', new_event_report_path(event_id:@event.id), class: "profile-edit-btn mt-1 pr-0 text-danger"%>
            </div>
          <%end %>

          <% elsif admin_signed_in?%>
          <div class="row">
            <%= link_to "Edit Event", edit_event_path , class: "profile-edit-btn mr-1 text-info"%>
          </div>
          <div class="row">
            <%= link_to 'Delete Event', event_path(@event.id), method: :delete, data: { confirm: 'Are you sure?' } , class: "profile-edit-btn mt-1 text-danger"%>
          </div>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
      </div>
      <div class="col-md-8">
        <div class="tab-content profile-tab" id="myTa=bContent">

          <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
            <div class="row">
              <% @event.event_guests.each do |guest| %>
                <div class="col-md-10">
                  <p> <i class="fas fa-user mr-1 text-dark"></i><%= link_to guest.user.username , guest.user %></p>
                </div>
              <% end %>
            </div>
          </div>
          <div class="tab-pane fade" id="comments" role="tabpanel" aria-labelledby="profile-tab">
            <div class="row">
              <button class="comment-create page-background ml-4"><%= link_to "Create Comment", new_comment_path(event_id:@event.id) , class: "comment-create mr-1 text-info"%></button>
              <% @event_comments.each do |comment| %>
                <% @replies = comment.replies %>
                <div class="col-md-10">
                  <div class="container">
                    <div class="card">
                      <div class="card-body">
                        <div class="row">
                          <div class="col-md-2">
                            <img src="https://image.ibb.co/jw55Ex/def_face.jpg" class="img img-rounded img-fluid"/>
                          </div>
                          <div class="col-md-10">
                            <p><u><%= link_to comment.event_guest.user.username, comment.event_guest.user %></u></p>
                            <div class="clearfix"></div>
                            <p><%= comment.message %></p>
                            <p class="text-secondary text-center small"><%= comment.created_at %></p>
                            <p>
                              <a class="float-right btn btn-outline-primary ml-2"> <i class="fa fa-reply"></i> Reply</a>
                            </p>
                          </div>
                          <% if user_signed_in? %>
                            <% if current_user.id==comment.event_guest.user.id %>
                            <button class="comment-create page-background mb-0"><%= link_to "Edit Comment", edit_comment_path(comment) , class: "comment-create mr-1 text-info"%></button>
                            <button class="comment-delete page-background mb-0"><%= link_to 'Delete Comment', comment_path(comment), method: :delete, class: "text-danger",data: { confirm: 'Are you sure?' } %> </button>
                            <%else %>
                            <button class="comment-delete page-background mb-0"><%= link_to 'Report Comment', new_comment_report_path(comment_id:comment.id), class: "profile-edit-btn mt-1 pr-0 text-danger"%></button>
                            <% end %>

                            <%elsif admin_signed_in? %>
                            <button class="comment-create page-background mb-0"><%= link_to "Edit Comment", edit_comment_path(comment) , class: "comment-create mr-1 text-info"%></button>
                            <button class="comment-delete page-background mb-0"><%= link_to 'Delete Comment', comment_path(comment.id), method: :delete, class: "text-danger",data: { confirm: 'Are you sure?' } %> </button>
                        <% end %>
                        </div>
                        <% @replies.each do |reply| %>
                          <div class="card card-inner">
                            <div class="card-body">
                              <div class="row">
                                <div class="col-md-2">
                                  <img src="https://image.ibb.co/jw55Ex/def_face.jpg" class="img img-rounded img-fluid"/>
                                </div>
                                <div class="col-md-10">
                                  <p><u><%= link_to reply.event_guest.user.username, reply.event_guest.user%></u></p>
                                  <p><%= reply.message %></p>
                                  <p class="text-secondary text-center small"><%= reply.created_at %></p>
                                </div>
                              </div>
                            </div>
                          </div>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
          <div class="tab-pane fade" id="start_date_poll" role="tabpanel" aria-labelledby="profile-tab">
            <div class="row">
              <% if user_signed_in? %>
              <% if current_user.id != @event.event_creator.user.id %>
                <% @current_guest = current_user.event_guests.where(event_id: @event.id).first %>
                <% if @current_guest.nil?%>
                  <p class="ml-3 mb-3 text-danger"> You need to be an event guest to vote!</p>
                  <%else %>
                <% if @current_guest.vote.present? %>
                <p class="ml-3 mb-3 text-success"> You already voted for option <%=@event.start_date_options.index(@current_guest.vote.start_date_option) +1 %>!</p>
                <%end %>
                  <%end %>
                  <%end %>
                <%@count = 1 %>
                <% @event.start_date_options.each do |option| %>
                <div class="col-md-10 mb-3">
                  <p class="text-dark">Option <%=@count%></p>
                  <p> <i class="fas fa-calendar-alt mr-1 text-dark"></i><%= option.possiblestartdate%></p>
                  <p>Current Votes: <%=option.votes.count %></p>
                  <% if @current_guest.nil? == false %>
                    <% unless @current_guest.vote.present? %>
                      <a class="big_title badge badge-pill bg-primary text-light mb-4" <%=link_to "Vote", new_vote_path(event_guest_id: @current_guest.id, start_date_option_id:option.id) %></a>
                      <%end %>
                    <%end %>
                </div>
                  <%@count+=1 %>
              <% end %>
                <%else %>
                <% @event.start_date_options.each do |option| %>
                  <div class="col-md-10 mb-3">
                    <p> <i class="fas fa-calendar-alt mr-1 text-dark"></i><%= option.possiblestartdate%></p>
                    <p>Current Votes: <%=option.votes.count %></p>
                  </div>
                  <%end %>
                <%end %>
            </div>
          </div>
          <div class="tab-pane fade" id="attachments" role="tabpanel" aria-labelledby="profile-tab">
            <div class="row">
              <div class="card ml-4 mb-3 ">
                <div class="card-header">
                  <h3>PDF attachments</h3>
                </div>
                <div class="card-body">
                  <% if @event.pdf.attached? %>

                    <% @event.pdf.each do |pdf| %>
                      <div class="mb-3">
                        <%= link_to pdf.blob.filename, url_for(pdf), class: "text-info" %>
                      </div>
                    <%end %>
                  <% else %>
                    <p class="ml-3">This event doesn't have any pdf attachments yet</p>
                  <% end %>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="card ml-4 mb-3 ">
                <div class="card-header">
                  <h3>Photo attachments</h3>
                </div>
                <div class="card-body">
                  <% if @event.pictures.attached? %>

                    <% @event.pictures.each do |picture| %>
                      <div class="mb-3">
                        <%= link_to image_tag(picture, class: "card-img-top", height: "150px", background: "#55595c", color: "#eceeef")%>
                      </div>
                    <%end %>
                  <% else %>
                    <p class="ml-3">This event doesn't have any photos attachments yet</p>
                  <% end %>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="card ml-4 mb-3 ">
                <div class="card-header">
                  <h3>Video attachments</h3>
                </div>
                <div class="card-body">
                  <% if @event.videos.attached? %>

                    <% @event.videos.each do |video| %>
                      <div class="mb-3">
                        <%= link_to video.blob.filename, url_for(video), class: "text-info" %>
                      </div>
                    <%end %>
                  <% else %>
                    <p class="ml-3">This event doesn't have any video attachments yet</p>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </form>
</div>