config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_for :admins, controllers: { sessions: 'admins/sessions' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :events , shallow: true do
        resources :comments
      end
      resources :comments
    end
  end


  resources :users, defaults: { format: :html}
  resources :comments, defaults: { format: :html}
  resources :events, defaults: { format: :html}
  resources :event_creators, defaults: { format: :html}
  resources :event_guests, defaults: { format: :html}
  resources :invitations, defaults: { format: :html}
  resources :mailboxes, defaults: { format: :html}
  resources :organizations, defaults: { format: :html}
  resources :organization_administrators, defaults: { format: :html}
  resources :replies, defaults: { format: :html}
  resources :start_date_options, defaults: { format: :html}
  resources :votes, defaults: { format: :html}
  resources :searches, default: { format: :html}
  resources :messages, defaults: {format: :html}
  resources :aup, default: { format: :html}
  resources :to_s, default: { format: :html}
  resources :event_reports, default: { format: :html}
  resources :comment_reports, default: { format: :html}
  resources :organization_reports, default: { format: :html}
  resource :total_report, default: { format: :html}
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

end

app/models/mailbox.rb
class Mailbox < ApplicationRecord
  belongs_to :user
  has_many :invitations, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/controllers/mailboxes_controller.rb
class MailboxesController < ApplicationController
  before_action :set_mailbox, only: [:show, :edit, :update, :destroy]

  # GET /mailboxes
  # GET /mailboxes.json
  def index
    @mailboxes = Mailbox.all
  end

  # GET /mailboxes/1
  # GET /mailboxes/1.json
  def show
    @invitations = @mailbox.invitations
    @messages = @mailbox.messages
  end

  # GET /mailboxes/new
  def new
    @mailbox = Mailbox.new
  end

  # GET /mailboxes/1/edit
  def edit
  end

  # POST /mailboxes
  # POST /mailboxes.json
  def create
    @mailbox = Mailbox.new(mailbox_params)

    respond_to do |format|
      if @mailbox.save
        format.html { redirect_to @mailbox, notice: 'Mailbox was successfully created.' }
        format.json { render :show, status: :created, location: @mailbox }
      else
        format.html { render :new }
        format.json { render json: @mailbox.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mailboxes/1
  # PATCH/PUT /mailboxes/1.json
  def update
    respond_to do |format|
      if @mailbox.update(mailbox_params)
        format.html { redirect_to @mailbox, notice: 'Mailbox was successfully updated.' }
        format.json { render :show, status: :ok, location: @mailbox }
      else
        format.html { render :edit }
        format.json { render json: @mailbox.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mailboxes/1
  # DELETE /mailboxes/1.json
  def destroy
    @mailbox.destroy
    respond_to do |format|
      format.html { redirect_to mailboxes_url, notice: 'Mailbox was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mailbox
      @mailbox = Mailbox.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mailbox_params
      params.fetch(:mailbox, {})
    end
end

app/helpers/mailboxes_helper.rb
module MailboxesHelper
end

app/views/mailboxes/_form.html.erb
<%= form_with(model: mailbox, local: true) do |form| %>
  <% if mailbox.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mailbox.errors.count, "error") %> prohibited this mailbox from being saved:</h2>

      <ul>
        <% mailbox.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mailboxes/edit.html.erb
<h1>Editing Mailbox</h1>

<%= render 'form', mailbox: @mailbox %>

<%= link_to 'Show', @mailbox %> |
<%= link_to 'Back', mailboxes_path %>

app/views/mailboxes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mailboxes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mailboxes.each do |mailbox| %>
      <tr>
        <td><%= link_to 'Show', mailbox %></td>
        <td><%= link_to 'Edit', edit_mailbox_path(mailbox) %></td>
        <td><%= link_to 'Destroy', mailbox, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mailbox', new_mailbox_path %>

app/views/mailboxes/new.html.erb
<h1>New Mailbox</h1>

<%= render 'form', mailbox: @mailbox %>

<%= link_to 'Back', mailboxes_path %>

app/views/mailboxes/show.html.erb
<div>
  <h3 class="text-center big_title">Invitations</h3>
  <% if @invitations.count == 0 %>
    <p class="text-center title-para">You haven't received any invitations yet!</p>
  <%else %>

    <% @invitations.each do |invitation| %>
      <div class="container">
        <div class="card mx-auto page-background">
          <div class="card-body">
            <div class="row ">
              <div class="col-md-2">
                <i class="fas fa-envelope fa-5x ml-5"></i>
              </div>
              <div class="col-md-10">
                <p>From: <%= link_to invitation.event.event_creator.user.username , invitation.event.event_creator.user %></p>
                <div class="clearfix"></div>
                <p><%= invitation.message %> <%=invitation.event.name %></p>
                <% @invitation_guest = @mailbox.user.event_guests.where(event_id:invitation.event.id).first %>
                <% if @invitation_guest.nil? %>
                  <button type="button" class="btn btn-sm btn-outline-secondary float-right">
                    <%= link_to "Accept", new_event_guest_path(event_id:invitation.event_id, user_id:@mailbox.user_id)%>
                  </button>
                <% else %>
                  <button type="button" class="btn btn-sm btn-outline-secondary float-right">Accepted</button>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <%end %>
</div>

<div class="mt-3 mb-5">
  <h3 class="text-center big_title">Messages</h3>
  <div class="text-center">
    <a class="big_title badge badge-pill bg-primary text-light mb-4 mx-auto" <%= link_to "Create New Message",new_message_path(user_id:current_user.id)%></a>
  </div>

  <% if @messages.count == 0 %>
    <p class="text-center title-para">You haven't recieved any messages yet!</p>
  <%else %>

    <% @messages.each do |message| %>
      <div class="container">
        <div class="card mx-auto page-background">
          <div class="card-body">
            <div class="row ">
              <div class="col-md-2">
                <i class="fas fa-envelope fa-5x ml-5"></i>
              </div>
              <div class="col-md-10">
                <p>From: <%= link_to message.user.username , message.user %></p>
                <div class="clearfix"></div>
                <p><%= message.message %></p>
                <button type="button" class="btn btn-sm btn-outline-secondary float-right">
                  <%= link_to "Reply", new_message_path(mailbox_id:message.user_id, user_id:current_user.id)%>
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <%end %>
</div>