config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_for :admins, controllers: { sessions: 'admins/sessions' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "pages#home"

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :events , shallow: true do
        resources :comments
      end
      resources :comments
    end
  end


  resources :users, defaults: { format: :html}
  resources :comments, defaults: { format: :html}
  resources :events, defaults: { format: :html}
  resources :event_creators, defaults: { format: :html}
  resources :event_guests, defaults: { format: :html}
  resources :invitations, defaults: { format: :html}
  resources :mailboxes, defaults: { format: :html}
  resources :organizations, defaults: { format: :html}
  resources :organization_administrators, defaults: { format: :html}
  resources :replies, defaults: { format: :html}
  resources :start_date_options, defaults: { format: :html}
  resources :votes, defaults: { format: :html}
  resources :searches, default: { format: :html}
  resources :messages, defaults: {format: :html}
  resources :aup, default: { format: :html}
  resources :to_s, default: { format: :html}
  resources :event_reports, default: { format: :html}
  resources :comment_reports, default: { format: :html}
  resources :organization_reports, default: { format: :html}
  resource :total_report, default: { format: :html}
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

end

app/models/organization.rb
class Organization < ApplicationRecord
  belongs_to :organization_administrator
  has_many :events, dependent: :destroy
  has_many :users
  before_destroy :kick_users
  has_one_attached :banner_picture
  has_one_attached :org_picture
  has_many_attached :pdf
  has_many_attached :pictures
  has_many_attached :videos


  validates :description, :name, presence: true
  before_destroy :update_org_admin_destroy
  after_create :update_org_admin_create


  private
  def kick_users
    users=self.users
    users.update_all(organization_id:nil)
  end

  def update_org_admin_create
    organization_administrator.update(organization_id:id)
    organization_administrator.user.update(organization_id:id)
  end

  def update_org_admin_destroy
    organization_administrator.update(organization_id:nil)
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @organization_events = @organization.events
    @members = @organization.users
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def organization_params
      params.fetch(:organization, {}).permit(:name, :description, :banner_picture, :organization_administrator_id, :org_picture, pdf: [], pictures: [], videos: [])
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<div>
  <%= form_with model: organization, local: true do |form| %>
    <%= errors_for organization%>

    <% if user_signed_in?%>
    <% if organization.organization_administrator_id == nil %>
      <%= form.hidden_field :organization_administrator_id, value: current_user.id%>
      <%end %>
      <%end %>

    <div class="banner-img pt-2">
      <% if @organization.banner_picture.attached? %>
        <%= image_tag(@organization.banner_picture , class: "card-img-top", width: "100%", height: "200px", background: "#55595c", color: "#eceeef")%>
      <% else %>
        <%= image_tag("thumbnail.svg", class: "card-img-top", height: "200px", width: "100%", background:"#55595c", color: "#eceeef") %>
      <% end %>
      <div class="form-group m-0 p-0">
        <%= form.file_field :banner_picture, class: " file btn form-control-file" %>
      </div>
    </div>
    <div class="container emp-profile">
      <form method="post">
        <div  id=profile_row class="row m-0 p-0">
          <div class="col-md-4 ml-0">
            <div class="profile-img ">
              <% if @organization.org_picture.attached? %>
                <%= image_tag(@organization.org_picture, class: "card-img-top", height: "150px", background: "#55595c", color: "#eceeef")%>
              <% else %>
                <%=image_tag("thumbnail.svg", class: "card-img-top", height: "150px", background:"#55595c", color: "#eceeef") %>
              <% end %>
              <div class=" form-group m-0 p-0">
                <%= form.file_field :org_picture, class: " file btn form-control-file" %>
              </div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="profile-head">
              <div>
                <h6>
                  <div class="form-group">
                    <i class="fas fa-info-circle"> </i>
                    <%= form.label :name%>
                    <%= form.text_field :name , class: "form-control"%>
                  </div>
                </h6>
              </div>
              <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item ">
                  <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">About</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" id="profile-tab" data-toggle="tab" href="#attachments" role="tab" aria-controls="profile" aria-selected="false">Attachments</a>
                </li>
              </ul>
            </div>
          </div>

        </div>
        <div class="row">
          <div class="col-md-4 pt-5 ml-3">
            <div class="profile-work">
            </div>
          </div>

          <div class="col-md-7">
            <div class="tab-content profile-tab" id="myTabContent">
              <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                <div class="row pt-2">
                  <% if admin_signed_in? %>
                    <% @non_org_admins = OrganizationAdministrator.where(organization_id:nil) %>
                  <div class="col-md-12">
                    <div class="form-group pt-1">
                      <%= form.label :Organization_administrator %>
                      <%= form.collection_select :organization_administrator_id, @non_org_admins,:id,:id, include_blank: true ,class: "form-control"%>
                    </div>
                  </div>
                    <%end %>
                  <div class="col-md-3">
                    <div class="form-group pt-1">
                      <%= form.label :description%>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <%= form.text_area :description, class: "form-control" %>
                  </div>
                </div>
              </div>

              <div class="tab-pane fade" id="attachments" role="tabpanel" aria-labelledby="profile-tab">
                <div class="row mb-3 mt-3">
                  <div class="text-center">
                      <p class="ml-3">Add pdf attachments here</p>
                      <%= form.file_field :pdf, multiple: true %>
                  </div>
                </div>
                <div class="row mb-3">
                  <div class="text-center">
                    <p class="ml-3">Add picture attachments here</p>
                    <%= form.file_field :pictures, multiple: true %>
                  </div>
                </div>
                <div class="row mb-3">
                  <div class="text-center">
                    <p class="ml-3">Add video attachments here</p>
                    <%= form.file_field :videos, multiple: true %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </form>
      <div class="form-group mt-2 text-center">
        <%= form.submit submit_btn_text, class: ["btn", "btn-primary"] %>
        <%= link_to "Back", :back, class: ["btn", "btn-secondary"] %>
      </div>
    </div>
  <% end %>
</div>

app/views/organizations/_organization.html.erb
<div class="card page-background mx-auto w-50 mt-2 mb-2">
  <h3> <i class="fas fa-users mr-2"></i><%= link_to organization.name, organization, class: "text-info" %></h3>
</div>

app/views/organizations/edit.html.erb
<div class="text-center ml-0 mt-3">
  <h2>Edit "<%=@organization.name%>" Organization</h2>
</div>
<div class="text-center ml-0 mt-2">
  <p>Please enter the required information to edit your organization:</p>
</div>
<%= render partial: "form",
           locals: {
               organization: @organization,
               submit_btn_text: "Update",
           } %>

app/views/organizations/index.html.erb
<div class="text-center">
  <h3 class="big_title">Organizations</h3>
  <% if user_signed_in? %>
    <% if current_user.organization_administrator.organization_id.nil?%>
  <a class="big_title badge badge-pill bg-primary text-light mb-4" <%= link_to "Create New Organization",new_organization_path %></a>
      <%else %>
    <p> You are already an organization administrator of <%=current_user.organization.name %></p>
      <%end %>
    <%elsif admin_signed_in?%>
    <a class="big_title badge badge-pill bg-primary text-light mb-4" <%= link_to "Create New Organization",new_organization_path %></a>
    <%end %>
  <% @organizations.each do |organization| %>
    <div class="card mb-4 shadow-sm mx-auto w-50">
      <div class="card-header">
        <h3 id="event_org"><%= organization.name %></h3>
      </div>
      <% if organization.org_picture.attached? %>
        <%= link_to image_tag(organization.org_picture, class: "card-img-top", height: "318.75px" ,background: "#55595c", color: "#eceeef"), url_for(organization) %>
      <% else %>
        <%=link_to image_tag("thumbnail.svg", class: "card-img-top", background:"#55595c", color: "#eceeef") , url_for(organization)%>
      <% end %>
      <div class="card-body">
        <p class="card-text"><%= organization.description%></p>
        <p class="card-text"><i class="fas fa-users mr-1 fa-lg"> </i><%= organization.users.count%></p>
        <button type="button" class="btn btn-sm btn-outline-secondary"> <%= link_to "See organization" , organization%></button>
      </div>
    </div>
  <% end %>
</div>

app/views/organizations/new.html.erb
<div class="text-center ml-0 mt-3">
  <h2>Create New Organization</h2>
</div>
<div class="text-center ml-0 mt-2">
  <p>Please enter the required information to create a new organization:</p>
</div>
<%= render partial: "form",
           locals: {
               organization: @organization,
               submit_btn_text: "Create",
           } %>

app/views/organizations/show.html.erb
<div>
  <% if @organization.banner_picture.attached? %>
    <%= image_tag(@organization.banner_picture, class: "card-img-top", width: "100%", height: "200px", background: "#55595c", color: "#eceeef")%>
  <% else %>
    <%= image_tag("thumbnail.svg", class: "card-img-top", height: "200px", width: "100%", background:"#55595c", color: "#eceeef") %>
  <% end %>
</div>
<div class="container emp-profile">
  <form method="post">
    <div class="row">
      <div class="col-md-4">
        <div class="profile-img">
          <% if @organization.org_picture.attached? %>
            <%= link_to image_tag(@organization.org_picture, class: "card-img-top", height: "150px", background: "#55595c", color: "#eceeef")%>
          <% else %>
            <%= link_to image_tag("thumbnail.svg", class: "card-img-top", height: "150px", background:"#55595c", color: "#eceeef") %>
          <% end %>
        </div>
      </div>
      <div class="col-md-6">
        <div class="profile-head">
          <h4>
            <%= @organization.name%>
          </h4>
          <h6>
            <i class="fas fa-users mr-1 fa-lg text-dark"> </i><%= @organization.users.count %>
          </h6>
          <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item">
              <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Description</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Members</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="profile-tab" data-toggle="tab" href="#events" role="tab" aria-controls="profile" aria-selected="false">Events</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="profile-tab" data-toggle="tab" href="#attachments" role="tab" aria-controls="profile" aria-selected="false">Attachments</a>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md-2">
        <%if user_signed_in? %>
        <% if @organization.organization_administrator.user_id == current_user.id %>
        <div class="row">
          <%= link_to "Edit Organization", edit_organization_path , class: "profile-edit-btn mr-1 text-info"%>
        </div>
        <div class="row">
          <%= link_to 'Delete Organization', organization_path(@organization.id), method: :delete, data: { confirm: 'Are you sure?' } , class: "profile-edit-btn mt-1 pr-0 text-danger"%>
        </div>
          <% else %>
            <div class="row">
              <%= link_to 'Report Organization', new_organization_report_path(organization_id:@organization.id), class: "profile-edit-btn mt-1 pr-0 text-danger"%>
            </div>
          <%end %>
        <% elsif admin_signed_in? %>
            <div class="row">
              <%= link_to "Edit Organization", edit_organization_path , class: "profile-edit-btn mr-1 text-info"%>
            </div>
            <div class="row">
              <%= link_to 'Delete Organization', organization_path(@organization.id), method: :delete, data: { confirm: 'Are you sure?' } , class: "profile-edit-btn mt-1 pr-0 text-danger"%>
            </div>
        <%end %>
        </div>
    </div>
    <div class="row">
      <div class="col-md-4">
      </div>
      <div class="col-md-8">
        <div class="tab-content profile-tab" id="myTabContent">
          <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
            <div class="row">
              <div class="col-md-6">
                <p> <%= @organization.description %></p>
              </div>
            </div>
          </div>
          <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
            <div class="row">
              <% @members.each do |member|%>
                <div class="col-md-10">
                  <p> <i class="fas fa-user mr-1 text-dark"></i><%= link_to member.username , member %></p>
                </div>
              <% end %>
            </div>
          </div>
          <div class="tab-pane fade" id="events" role="tabpanel" aria-labelledby="profile-tab">
            <%if user_signed_in? %>
            <% if @organization.id == current_user.organization_id %>
            <h6 class="mb-2">These are all the events of this organization </h6>
              <%else %>
              <h6 class="mb-2">These are the public events of this organization </h6>
              <%end %>
            <div class="row">
              <div class="text-center">
                <% @organization_events.each do |event|%>
                  <% if @organization.id == current_user.organization_id %>
                    <div class="col-md-14">
                      <div class="card mb-4 shadow-sm mx-auto">
                        <div class="card-header">
                          <h3 id="event_org"><%= event.name %></h3>
                        </div>
                        <div class="card-body">
                          <p class="card-text">Description: <%= event.description%></p>
                          <p class="card-text"> <i class="fas fa-location-arrow mr-1 fa-lg text-dark"></i> <%= event.location %></p>
                          <button type="button" class="btn btn-sm btn-outline-secondary"> <%= link_to "See event" , event%></button>
                        </div>
                      </div>
                    </div>
                  <% else %>
                    <% if event.publicEvent == true %>
                    <div class="col-md-14">
                      <div class="card mb-4 shadow-sm mx-auto">
                        <div class="card-header">
                          <h3 id="event_org"><%= event.name %></h3>
                        </div>
                        <div class="card-body">
                          <p class="card-text">Description: <%= event.description%></p>
                          <p class="card-text"> <i class="fas fa-location-arrow mr-1 fa-lg text-dark"></i> <%= event.location %></p>
                          <button type="button" class="btn btn-sm btn-outline-secondary"> <%= link_to "See event" , event%></button>
                        </div>
                      </div>
                    </div>
                    <% end %>
                  <%end %>
                <% end %>
            <% elsif admin_signed_in?%>
              <h6 class="mb-2">These are all the events of this organization </h6>
            <div class="row">
              <div class="text-center">
                <% @organization_events.each do |event|%>
                    <div class="col-md-14">
                      <div class="card mb-4 shadow-sm mx-auto">
                        <div class="card-header">
                          <h3 id="event_org"><%= event.name %></h3>
                        </div>
                        <div class="card-body">
                          <p class="card-text">Description: <%= event.description%></p>
                          <p class="card-text"> <i class="fas fa-location-arrow mr-1 fa-lg text-dark"></i> <%= event.location %></p>
                          <button type="button" class="btn btn-sm btn-outline-secondary"> <%= link_to "See event" , event%></button>
                        </div>
                      </div>
                    </div>
                  <%end %>
            <%end %>
              </div>
            </div>
          </div>
          <div class="tab-pane fade" id="attachments" role="tabpanel" aria-labelledby="profile-tab">
            <div class="row">
              <div class="card ml-4 mb-3 ">
                <div class="card-header">
                  <h3>PDF attachments</h3>
                </div>
                <div class="card-body">
                  <% if @organization.pdf.attached? %>

                    <% @organization.pdf.each do |pdf| %>
                      <div class="mb-3">
                        <%= link_to pdf.blob.filename, url_for(pdf), class: "text-info" %>
                      </div>
                    <%end %>
                  <% else %>
                    <p class="ml-3">This organizations hasn't any pdf attachments yet</p>
                  <% end %>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="card ml-4 mb-3 ">
                <div class="card-header">
                  <h3>Photo attachments</h3>
                </div>
                <div class="card-body">
                  <% if @organization.pictures.attached? %>

                    <% @organization.pictures.each do |picture| %>
                      <div class="mb-3">
                        <%= link_to image_tag(picture, class: "card-img-top", height: "150px", background: "#55595c", color: "#eceeef")%>
                      </div>
                    <%end %>
                  <% else %>
                    <p class="ml-3">This organizations hasn't any photos attachments yet</p>
                  <% end %>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="card ml-4 mb-3 ">
                <div class="card-header">
                  <h3>Video attachments</h3>
                </div>
                <div class="card-body">
                  <% if @organization.videos.attached? %>

                    <% @organization.videos.each do |video| %>
                      <div class="mb-3">
                        <%= link_to video.blob.filename, url_for(video), class: "text-info" %>
                      </div>
                    <%end %>
                  <% else %>
                    <p class="ml-3">This organizations hasn't any video attachments yet</p>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
      </div>
    </div>
  </form>
</div>